{{- if .Values.warmPool.enabled }}
apiVersion: extensions.agents.x-k8s.io/v1beta1
kind: SandboxWarmPool
metadata:
  name: {{ .Values.sandboxTemplate.name }}-pool
  namespace: {{ .Values.gateway.namespace }}
spec:
  replicas: {{ .Values.warmPool.replicas }}
  sandboxTemplateRef:
    name: {{ .Values.sandboxTemplate.name }}
  updateStrategy:
    type: OnReplenish
{{- end }}
