apiVersion: v1
kind: Service
metadata:
  name: {{ include "openshell-playground-plugin.fullname" . }}
  labels:
    {{- include "openshell-playground-plugin.labels" . | nindent 4 }}
  annotations:
    {{- if .Values.tls.enabled }}
    service.alpha.openshift.io/serving-cert-secret-name: {{ include "openshell-playground-plugin.fullname" . }}-tls
    {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.plugin.port }}
      protocol: TCP
  selector:
    {{- include "openshell-playground-plugin.selectorLabels" . | nindent 4 }}
